[advisories]
unmaintained = "allow"
ignore = [
    "RUSTSEC-2020-0071",
]

[bans]
# Accept some duplicate versions, ideally we work towards this list
# becoming empty.  Adding versions forces us to revisit this at least
# when upgrading.
# Please keep this list alphabetically sorted.
skip = [
     { name = "ahash", version = "0.7.6" },
     { name = "base64", version = "<0.21" },
     { name = "bitflags", version = "1.3.2" },
     { name = "fastrand", version = "<2.0.0" },
     { name = "getrandom", version = "<0.2" },
     { name = "hashbrown", version = "<0.14.0" },
     { name = "idna", version = "<0.3" },
     { name = "indexmap", version = "<2.0.0" },
     { name = "quick-error", version = "<2.0" },
     { name = "rand_chacha", version = "<0.3" },
     { name = "rand_core", version = "<0.6" },
     { name = "rand", version = "<0.8" },
     { name = "redox_syscall", version = "0.2.16" },
     { name = "regex-automata", version = "<0.3.3" },
     { name = "regex-syntax", version = "0.6.29" },
     { name = "rustls-webpki", version = "<0.101.1" },
     { name = "socket2", version = "0.4.9" },
     { name = "sha1", version = "<0.10.5" },
     { name = "spin", version = "<0.9.6" },
     { name = "syn", version = "1.0.109" },
     { name = "time", version = "<0.3" },
     { name = "wasi", version = "<0.11" },
     { name = "webpki-roots", version = "<0.23.1" },
     { name = "winreg", version = "0.10.1" },
]


[licenses]
allow = [
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0", # Boost Software License 1.0
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-DFS-2016",
    "Zlib",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
      { path = "LICENSE", hash = 0xbd0eed23 },
]

[sources.allow-org]
# Organisations which we allow git sources from.
github = [
       "async-email",
       "deltachat",
]
